# .github/workflows/add_issues_to_project.yml

name: Issue Project Automation

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  automate-project:
    runs-on: ubuntu-latest
    steps:
    - name: Add to Project
      uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: '引っ越しに必要なもの'
        column: '買い出し前'
        repo-token: ${{ secrets.GITHUB_TOKEN }}